(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var J3=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.ORa)("0",Math.max(0,b-c))+a},HWa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},IWa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},L3=function(a){"number"===typeof a?(this.date=JWa(a,0,1),K3(this,1)):g.Ra(a)?(this.date=JWa(a.getFullYear(),a.getMonth(),a.getDate()),K3(this,a.getDate())):(this.date=new Date(g.Xa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),K3(this,a))},JWa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},K3=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},M3=function(a,b){g.mM.call(this,a,{G:"div",
L:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},V:[{G:"div",L:"ytp-reminder-menu-contents",V:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.j=b;this.B=[];this.menuPopupRenderer=void 0;this.items=this.Da("ytp-reminder-menu-items");this.hide()},LWa=function(a){var b=KWa(a),c=0,d={};
for(c=0;c<b.length;d={AC:d.AC},c++){var e=a.B[c];e||(e=new g.U({G:"div",L:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},V:[{G:"div",L:"ytp-reminder-menu-item-icon",oa:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",oa:"{{text}}"}]}),d.AC=c,e.Pa("click",function(l){return function(){var m=l.AC;a.Fb();m=KWa(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ba(a.items),a.B[c]=e);
var f=b[c],k=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":k=HWa();break;case "NOTIFICATIONS_NONE":k=IWa();break;case "NOTIFICATIONS_ACTIVE":k=g.II()}f=f.text?g.Xw(f.text):"";e.update({icon:k,text:f})}for(;c<a.B.length;)a.B.pop().dispose();0===c?a.Fb():a.pd(a.j)},KWa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},N3=function(a){g.U.call(this,{G:"div",
V:[{G:"button",Ha:["ytp-offline-slate-button","ytp-button"],V:[{G:"div",L:"ytp-offline-slate-button-icon",oa:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",oa:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.j=null;(this.D=this.Da("ytp-offline-slate-button"))&&this.T(this.D,"click",this.J);this.hide()},MWa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);O3(a)},O3=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.Xw(b.toggledText):"";a.update({text:c,icon:P3(b.toggledIcon)})}else c=b.defaultText?g.Xw(b.defaultText):"",a.update({text:c,icon:P3(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=NWa(a))?(c=b.text?g.Xw(b.text):"",a.update({text:c,icon:P3(b.icon)}),a.show()):a.hide():a.hide()},PWa=function(a,b,c){a.C||(a.C=new g.hv(a.I.U().gh));
var d={context:g.lt(a.C.config_||g.mt())};g.Tv()&&(d.context.clientScreenNonce=g.Tv());d.params=c;g.nt(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){OWa(a)},
onTimeout:function(){OWa(a)}})},OWa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,O3(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,O3(a))},P3=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return HWa();case "NOTIFICATIONS_NONE":return IWa();case "NOTIFICATIONS_ACTIVE":return g.II();default:return null}},NWa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},Q3=function(a){g.U.call(this,{G:"div",
L:"ytp-offline-slate",V:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",V:[{G:"span",L:"ytp-offline-slate-icon",V:[{G:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{G:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",V:[{G:"div",L:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},oa:"{{mainText}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",oa:"{{subtitleText}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",Ha:["ytp-offline-slate-close-button","ytp-button"],V:[g.DI()]},{G:"button",Ha:["ytp-offline-slate-open-button","ytp-button"],V:[g.CI()]},{G:"div",L:"ytp-offline-slate-trailer-chip",oa:"Trailer"}]});var b=
this;this.api=a;this.j=this.u=null;this.background=this.Da("ytp-offline-slate-background");this.B=this.Da("ytp-offline-slate-bar");this.D=new g.J(function(){g.Ip(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.C=new g.J(function(){g.Ip(b.element,"ytp-offline-slate-collapsed")},15E3);
g.I(this,this.C);g.I(this,this.D);this.countdownTimer=new g.J(this.sQ,1E3,this);this.T(a,"presentingplayerstatechange",this.vQ);this.T(a,"livestatedata",this.Ka);a=this.Da("ytp-offline-slate-close-button");this.T(a,"click",function(){g.Ip(b.element,"ytp-offline-slate-collapsed")});
a=this.Da("ytp-offline-slate-open-button");this.T(a,"click",function(){g.Kp(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Ka(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().rj;var c=8===this.api.getPresentingPlayerType();g.L(this.element,"ytp-offline-slate-premiere-trailer",a);g.L(this.element,"ytp-offline-slate-hide-background",c)},R3=function(a,b,c){var d,e,f,k;
if(b){var l=null!=b.subtitleText?g.Xw(b.subtitleText):"";c=c?c:null!=b.mainText?g.Xw(b.mainText):"";b=null!==(k=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==k?k:c;a.update({mainText:c,subtitleText:l,label:b});g.L(a.element,"ytp-offline-slate-single-text-line",!l);g.L(a.B,"ytp-offline-slate-bar-hidden",!c&&!l)}},S3=function(a,b){var c=(0,g.P)();
this.trigger=a;this.j=b;this.B=c},U3=function(a){g.BL.call(this,a);
var b=this;this.K=!1;this.N=0;this.D=!1;this.u=new g.J(function(){var e=b.player.U(),f=b.getVideoData();if(T3(b))if(QWa(b)){var k;null!==(k=b.heartbeatParams)&&void 0!==k&&k.url&&(e=g.Gj(b.heartbeatParams.url,{request_id:g.$oa()}),f.Ja&&(e=g.Gj(e,{vvt:f.Ja}),f.mdxEnvironment&&(e=g.Gj(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Gj(e,{access_token:f.oauthToken})),RWa(b,f,e))}else SWa(b),TWa(b,e,f)},0);
this.j=this.heartbeatParams=null;this.C=!1;this.J=new g.oj(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Z=new g.hv(void 0);this.X=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new L3).date.getTimezoneOffset();this.B=new g.oA(this);g.I(this,this.u);g.I(this,this.B);SWa(this);UWa(this);this.B.T(a,"heartbeatparams",this.yx);this.B.T(a,"presentingplayerstatechange",this.wS);this.B.T(a,"videoplayerreset",this.xS);this.B.T(a,g.Sw("heartbeat"),this.onCueRangeEnter);this.C&&this.j&&
VWa(this,this.j);var c=new g.Qw(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.Qw(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Od([c,d]);WWa(this)},WWa=function(a){var b=a.getVideoData();
b.nh&&(b=b.botguardData)&&g.zK(b,a.player.U())},SWa=function(a){var b=a.getVideoData();
if(b.nh&&(b=new g.vBa(b),g.vK.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Sa){var d=g.wBa(b);if(d){c={};var e={};d=d.split("&");d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=XWa[Number(e.r1c)]);c.challenge=b.videoData.Sa}}a.attestationResponse=c||void 0}},QWa=function(a){var b=a.getVideoData();
if(!g.tE(a.getVideoData())||b.aJ)return!1;if(b.useInnertubeDrmService()&&b.N){a="playready"===b.N.flavor&&b.S("html5_innertube_heartbeats_for_playready");var c="widevine"===b.N.flavor&&b.S("html5_innertube_heartbeats_for_widevine");b=g.wB(b.N)&&b.S("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},V3=function(a){if(QWa(a))return!!a.heartbeatParams;
var b=a.player.U(),c=a.getVideoData();return b.S("html5_heartbeat_wait_for_drm_killswitch")||!g.tE(a.getVideoData())||!c.useInnertubeDrmService()||c.Yf||c.tH?!!c.heartbeatToken:!1},W3=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(V3(a)||c.isLivePlayback){if(void 0===b)if(a.D){var d;b=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().SI||6E4}else b=1E3;a.u.start(b)}}},RWa=function(a,b,c){b.vk&&(c=g.Gj(c,{internalipoverride:b.vk}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.rb&&(d.kpt=b.rb);c=g.Gj(c,d);g.Or(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&T3(a)){a.J.reset();a.sequenceNumber++;e=e.responseText;var f=YWa(e);if(f){a.player.Qa("onHeartbeat",f);var k="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else k=(k=e.match(ZWa))?"0"===k[1]?0:1:-1;$Wa(a,f,e,k)}},
onError:function(e){T3(a)&&X3(a,!0,"net-"+e.status)},
onTimeout:function(){T3(a)&&X3(a,!0,"timeout")},
withCredentials:!0})},T3=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.T(a.player.zb(a.getPlayerType()),4)?!1:V3(a)||b.isLivePlayback?!0:(Y3(a),!1)},TWa=function(a,b,c){var d,e,f,k={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!==(d=a.ma)&&void 0!==d?d:c.heartbeatServerData};a.X=a.attestationResponse;c.nh&&(k.attestationResponse=a.X);var l=g.EK(c),m=null!==(e=l.client)&&void 0!==e?e:{};m.utcOffsetMinutes=a.utcOffsetMinutes;k.context=l;k.cpn=c.clientPlaybackNonce;if(l="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=l;m={heartbeatChecks:[]};if(l=c.getPlayerResponse())c.heartbeatToken&&(k.heartbeatToken=c.heartbeatToken),
(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.eD(b)){m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var n=aXa(a);l={};null!==n&&(l.clientPlayerPositionUtcMillis=n);n=null===(f=a.player.ub())||void 0===f?void 0:g.QL(f);n=(null===n||void 0===n?void 0:n.freePreviewWatchedDuration)||0;0<n&&(l.freePreviewWatchedDuration={seconds:""+
n});m.unpluggedParams=l}k.heartbeatRequestParams=m;b.S("enable_linear_player_handling")&&c.isLivePlayback&&(b=aXa(a),null!==b&&(k.playbackState||(k.playbackState={}),k.playbackState.playbackPosition={utcTimeMillis:b}));b={timeout:3E4,onSuccess:function(p){var r;if(!a.u.isActive()&&T3(a)){var t=a.getVideoData(),u=t.nh&&null==a.X;t.nh=!(null===(r=p.heartbeatAttestationConfig)||void 0===r||!r.requiresAttestation)||u;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.Aa("authshear",
{});u=-1;var x=p.playabilityStatus;x&&(a.player.Qa("onHeartbeat",x),"OK"===x.status?u=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?u=1:"LIVE_STREAM_OFFLINE"===x.status&&(u=0));a.sequenceNumber&&-1===u||a.J.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.ma=p.heartbeatServerData);$Wa(a,r,t,u)}},
onError:function(p){T3(a)&&X3(a,!0,"net-"+p.status)},
onTimeout:function(){T3(a)&&X3(a,!0,"timeout")}};
g.JE(c)&&(b.ZK="Bearer "+g.JE(c));g.nt(a.Z,"player/heartbeat",k,b)},$Wa=function(a,b,c,d){-1===d?(b="decode "+g.Kc(c),X3(a,!1,b)):2===d?(Y3(a),a.D=!0):(a.N=0,a.u.stop(),1===d?(a.D=!1,a.player.Tf("heartbeat.stop",2,a.Ee(c)),g.Et("heartbeatActionPlayerHalted",bXa(b))):(a.D=!0,c=0,a.C&&b&&(c=VWa(a,b),a.player.ea("livestatedata",b)),c?W3(a,c):W3(a)))},VWa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!(e.switchStreamsImmediately||e.transitionTiming&&
"STREAM_TRANSITION_TIMING_IMMEDIATELY"===e.transitionTiming)),k=cXa(e),l=a.getVideoData(),m=a.player.zb(a.getPlayerType()),n=m.Jc()&&!g.xE(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(2<=l.U().X){var p=(null===(c=a.player.xd())||void 0===c?void 0:c.Nb())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;p.ended=""+ +!(!e||!e.displayEndscreen);a.player.Aa("heartbeat",p)}if(n&&!f)return k;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().GN=f;else{if(n=f)(n=f&&f.videoId)?(a.player.nk(n,{autonav:"1"},void 0,!0,!0,f),a.TA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return k}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.S("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.kb||p)return e={video_id:l.videoId},l.LC&&(e.is_live_destination="1"),a.player.S("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.force_gvi=l.dh,e.Li=l.Li,m=void 0,l.hlsvp||l.kb?p&&(m=new S3("broadcastIdChanged",n+","+f),a.TA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new S3("formatsReceived",""+f)),a.TA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,void 0,m),k;a.player.He("heartbeat",a.getPlayerType())}e&&
e.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.J=!0,a.vb&&a.api.Au()):g.JH(m)&&(l=(null===(d=a.player.xd())||void 0===d?void 0:d.Nb())||{},a.player.Aa("hbse",l,!0),a.player.Au(),a.player.Qa("onLiveMediaEnded",b)));return k},cXa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},X3=function(a,b,c){if(!a.u.isActive()){a.u.stop();
a.N++;var d=a.getVideoData();if(d.UI||b&&!g.tE(a.getVideoData())&&!V3(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.uu)?f=a.heartbeatParams.uu:f=d.TI||5;e=a.N>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=bXa()),g.Et("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Tf(b,1,"Video playback interrupted. Please try again.",c):a.player.Tf(b,1,"Sorry, there was an error licensing this video.",
c)):(W3(a,a.J.getValue()),g.pj(a.J))}},bXa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},Y3=function(a){a.N=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},UWa=function(a){var b,c=a.getVideoData(),d=a.player.U();
if(c.isLivePlayback)if(g.EB(d.u)){a.C=!0;a.K=!0;if(!g.UC(d)||g.eD(d))a.offlineSlate=new Q3(a.player),g.I(a,a.offlineSlate),g.oL(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.j=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.j)||void 0===b?void 0:b.status)||a.player.S("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.j?(c=cXa(a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?W3(a,c):W3(a,7500):W3(a,1E3)}else a.player.Tf("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!d.S("html5_release_post_live_heartbeat_killswitch")&&g.cc(c.ma,"heartbeat")&&a.player.He("heartbeat",a.getPlayerType())},aXa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},YWa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},XWa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],dXa={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),
SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),
SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},Z3=dXa;Z3=dXa;g.h=L3.prototype;g.h.VL=Z3.FIRSTDAYOFWEEK;g.h.WL=Z3.FIRSTWEEKCUTOFFDAY;g.h.clone=function(){var a=new L3(this.date);a.VL=this.VL;a.WL=this.WL;return a};
g.h.getFullYear=function(){return this.date.getFullYear()};
g.h.getMonth=function(){return this.date.getMonth()};
g.h.getDate=function(){return this.date.getDate()};
g.h.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.h.add=function(a){if(a.u||a.j){var b=this.getMonth()+a.j+12*a.u,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(c=this.getFullYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),
this.date.setFullYear(a.getFullYear()+b),this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),K3(this,a.getDate()))};
g.h.equals=function(a){return!(!a||this.getFullYear()!=a.getFullYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.h.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+J3(Math.abs(a),b?6:4),J3(this.getMonth()+1,2),J3(this.getDate(),2)].join("")+""};
g.h.valueOf=function(){return this.date.valueOf()};g.v(M3,g.mM);M3.prototype.hide=function(){this.j&&this.j.removeAttribute("aria-haspopup");g.mM.prototype.hide.call(this)};
M3.prototype.show=function(){this.j&&this.j.setAttribute("aria-haspopup","true");g.mM.prototype.show.call(this)};
M3.prototype.ra=function(){g.sf(this.B);g.mM.prototype.ra.call(this)};g.v(N3,g.U);
N3.prototype.J=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;O3(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.vb)this.j.Fb();else{var b=NWa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.j||(this.j=new M3(this.I,this.D),this.j.Ba(this.element),g.I(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.B,this));b=this.j;b.menuPopupRenderer=a;LWa(b)}};
N3.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(PWa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;O3(this);break}}};g.v(Q3,g.U);g.h=Q3.prototype;g.h.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.h.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.h.Ka=function(a){var b,c,d=null===(c=null===(b=null===a||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate;if(d){this.u=a;d=d.liveStreamOfflineSlateRenderer;d.canShowCountdown?this.sQ():R3(this,d);var e,f,k,l,m=null===(l=null===(k=null===(f=null===(e=null===a||void 0===a?void 0:a.liveStreamability)||void 0===e?void 0:e.liveStreamabilityRenderer)||void 0===f?void 0:f.offlineSlate)||void 0===k?void 0:k.liveStreamOfflineSlateRenderer)||
void 0===l?void 0:l.thumbnail;if(m){e=0;f=null;m=m.thumbnails;for(k=0;k<m.length;k++)m[k].width>e&&(e=m[k].width||0,f=m[k].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";d.actionButtons||d.reminderButton?(this.j||(this.j=new N3(this.api),this.j.Ba(this.Da("ytp-offline-slate-buttons")),g.I(this,this.j)),MWa(this.j,d.actionButtons&&d.actionButtons[0],d.reminderButton)):this.j&&MWa(this.j,null,null);this.u=a}else this.u=null;this.vQ()};
g.h.vQ=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.zb(),d=this.getVideoData();b=d.isLivePlayback&&(g.JH(c)||g.T(c,2)||g.T(c,64));var e=2===d.autonavState&&g.T(c,2);c=c.Jc()&&!g.xE(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.vb?(null===a||void 0===a?0:g.GF(a,2))&&!this.getVideoData().rj&&(g.Kp(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.Kp(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.J&&this.api.Au()):this.vb&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.h.sQ=function(){var a,b,c,d,e=null===(d=null===(c=null===(b=null===(a=this.u)||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate)||void 0===d?void 0:d.liveStreamOfflineSlateRenderer;if(e){var f=Math.floor(g.Xa()/1E3),k=e.canShowCountdown&&Number(e.scheduledStartTime);!k||k<=f?(R3(this,e),this.countdownTimer.stop()):(f=g.wJ(k-f),R3(this,e,f),g.Bp(this.countdownTimer))}};
g.h.ra=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.ra.call(this)};S3.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.j===a.j:!1};
S3.prototype.isExpired=function(){return 6E4<(0,g.P)()-this.B};
S3.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.j};g.v(U3,g.BL);g.h=U3.prototype;g.h.ra=function(){Y3(this);this.player.jf("heartbeat");g.BL.prototype.ra.call(this)};
g.h.onCueRangeEnter=function(){this.K=!0;W3(this,2E3)};
g.h.yx=function(a){this.heartbeatParams=a;W3(this,2E3)};
g.h.wS=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.j)||void 0===b?void 0:b.status)&&!this.player.S("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.T(a.state,2)||g.T(a.state,64)?(Y3(this),this.C&&(this.K=!0,W3(this,1E3))):(g.T(a.state,1)||g.T(a.state,8))&&W3(this,2E3))};
g.h.xS=function(){3!==this.player.getPresentingPlayerType()&&W3(this,2E3)};
g.h.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.h.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.h.Zh=function(a){switch(a){case 4:case 3:return!1}return!0};
g.h.TA=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Et("heartbeatActionPlayerTransitioned",a)};
g.h.Ee=function(a){var b="LICENSE",c=YWa(a);if(c)return c.reason||g.gM[b]||"";(a=a.match(ZWa))&&(a=Number(a[1]))&&(b=g.eya(a));return g.gM[b]||""};
g.h.Vw=function(){return!!this.offlineSlate&&this.offlineSlate.vb};
var ZWa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.AL("heartbeat",U3);})(_yt_player);
